name: Metal ðŸ¤˜

# Run long tests once nightly, at 00:00
on:
  pull_request:
    types:
      - labeled
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  metal-test-check:
    runs-on: ubuntu-24.04
    if: ${{ github.event_name == 'schedule' ||  github.event.label.name == 'metal-tests' }}
    steps:
      - name: Metal Test Check
        run: |
          echo "Metal tests are required."

  build-fw-artifact:
    needs: metal-test-check
    uses: ./.github/workflows/build-fw.yml
    secrets:
      SIGNATURE_KEY: ${{ secrets.SIGNATURE_KEY }}

  gen-config:
    needs: metal-test-check
    runs-on: ubuntu-24.04
    outputs:
      matrix-config: ${{ steps.gen-config.outputs.matrix-config }}
    steps:
      - uses: actions/checkout@v4
      - id: gen-config
        shell: bash
        run: |
          # Filter to only Blackhole boards (product == "bh"), then remove the product field
          MATRIX_CONFIG="$(jq -c '[.[] | select(.product == "bh") | del(.product)]' .github/ci_boards.json)"
          echo "matrix-config=$MATRIX_CONFIG" | tee -a $GITHUB_OUTPUT

  metal-test:
    needs: [build-fw-artifact, gen-config]
    strategy:
      fail-fast: false
      matrix:
        config: ${{ fromJson(needs.gen-config.outputs.matrix-config) }}
    runs-on: ${{ matrix.config.runs-on }}
    container:
      image: ${{ matrix.config.metal-image }}
      volumes:
        - /dev/hugepages-1G:/dev/hugepages-1G
        - /dev/hugepages:/dev/hugepages
        - /opt/tenstorrent/hf-models/:/opt/tenstorrent/hf-models/
        - /opt/tenstorrent/kmd-builds/:/opt/tenstorrent/kmd-builds/
      options: '--device /dev/tenstorrent --device /dev/bus/usb --privileged'
    env:
      ARCH_NAME: blackhole
      HOME: /home/user/tt-metal
      HF_MODEL: /opt/tenstorrent/hf-models/meta-llama/Llama-3.1-8B/
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.HOME }}
    steps:
      - name: Select tt-kmd
        shell: bash
        run: |
          sudo apt update || true
          sudo apt install -y kmod
          sudo rmmod tenstorrent
          sudo insmod /opt/tenstorrent/kmd-builds/${{ matrix.config.kmd_build }}/tenstorrent.ko
          echo "tt-kmd version: $(cat /sys/module/tenstorrent/version)"

      - id: mkdir-home-user-tt-metal
        run: |
          mkdir -p $HOME
      - name: Download the latest firmware bundle
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build-fw-artifact.outputs.combined-fwbundle-artifact }}
          path: ${{ env.HOME }}
      - name: Run the rescan-pcie.sh script
        run: |
          curl -o /tmp/rescan-pcie.sh https://raw.githubusercontent.com/tenstorrent/tt-zephyr-platforms/${{ github.sha }}/scripts/rescan-pcie.sh
          source /tmp/rescan-pcie.sh
      - name: Flash the firmware
        run: |
          python -m venv .env
          source .env/bin/activate
          pip install tt-flash==3.4.7
          tt-flash $HOME/fw_pack-*.fwbundle --force
      - name: Patch Test Command
        run: |
          # Patch whisper demo test to run with CI=false to skip the performance checks.
          # These tests fail on syseng CI because the runners have different configurations
          # than metal CI systems.
          sed -i 's/pytest\(.*\)test_demo_for_conditional_generation/CI=false pytest\1test_demo_for_conditional_generation/g' \
            dockerfile/upstream_test_images/run_upstream_tests_vanilla.sh
          # Running the resnet conv test once without determinism checks before
          # We enable the checks serves as a workaround for SYS-2705, where
          # P300 cards have different outputs on the first run after cold boot.
          SEARCH="echo \"\[upstream-tests\] Running BH upstream didt tests\""
          INSERT="    pytest tests/didt/test_resnet_conv.py::test_resnet_conv -k \"all\" --didt-workload-iterations 100 --determinism-check-interval 0"
          sed -i "/$SEARCH/a$INSERT" dockerfile/upstream_test_images/run_upstream_tests_vanilla.sh
          # To verify patch was applied
          git diff

      - name: Run Container Test
        run: |
          sh -c "dockerfile/upstream_test_images/run_upstream_tests_vanilla.sh ${{ matrix.config.metal-target }}"
      - name: cleanup
        if: ${{ always() }}
        run: |
          # Clean out metal
          rm -f $HOME/fw_pack-*.fwbundle
